In [5]:
import blasbooster as bb
import numpy as np

print("blasbooster version:",bb.__version__)
print("numpy version:", np.__version__)

blasbooster version: 0.3 revision fb5599d
numpy version: 1.17.3


In [2]:
np_A = np.random.rand(5, 5).astype(np.float32)
print(np_A)

[[0.9344637  0.69282615 0.75129825 0.9509893  0.01317367]
 [0.5693703  0.50178725 0.10449303 0.0769534  0.61917776]
 [0.6933893  0.6983037  0.34631586 0.3004619  0.5638619 ]
 [0.23356915 0.897028   0.30880734 0.24742821 0.91817826]
 [0.84505963 0.75320095 0.3488431  0.1414728  0.27972797]]


In [3]:
A = bb.Matrix(np_A)

In [4]:
print(A)

TypeError: __str__(): incompatible function arguments. The following argument types are supported:
    1. () -> str

Invoked with: <blasbooster.Matrix object at 0x7fa0e436b8f0>

In [ ]:
B = A * A